version: '3.8'

services:
  abitus-fe: 
    build:
      context: . 
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    container_name: abitus-frontend
    ports:
      - "3000:3000" 
    restart: unless-stopped
    env_file:
      - .env